/**
 * Generates `src/data/seed-organizations.json` — the fixture the app reads
 * when no DATABASE_URL and no IRS import are present.
 *
 * IMPORTANT: every organization below is FICTIONAL. Real Jewish charities are
 * not listed here, and no real payment handle appears anywhere in this file.
 * Publishing an invented Zelle address under a real charity's name would be
 * the exact failure mode §8 ranks as project-ending, so the demo fixture is
 * built from invented organizations and reserved-looking EINs (99-…).
 *
 * The real pipeline is `scripts/ingest-bmf.ts`, which writes the same shape
 * from the IRS Exempt Organizations Business Master File.
 *
 *   npx tsx scripts/build-demo-seed.ts
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";

type Json = Record<string, unknown>;

const TODAY = new Date("2026-08-21T00:00:00Z");

function daysAgo(n: number): string {
  return new Date(TODAY.getTime() - n * 86_400_000).toISOString();
}

let einCounter = 1001;
function demoEin(): string {
  return `99-${String(einCounter++).padStart(7, "0")}`;
}

interface Place {
  city: string;
  region: string;
  postalCode: string;
  lat: number;
  lng: number;
}

const PLACES: Record<string, Place> = {
  brooklyn: { city: "Brooklyn", region: "NY", postalCode: "11219", lat: 40.6323, lng: -73.9955 },
  lakewood: { city: "Lakewood", region: "NJ", postalCode: "08701", lat: 40.0979, lng: -74.2179 },
  monsey: { city: "Monsey", region: "NY", postalCode: "10952", lat: 41.1112, lng: -74.0682 },
  baltimore: { city: "Baltimore", region: "MD", postalCode: "21215", lat: 39.3489, lng: -76.6858 },
  chicago: { city: "Chicago", region: "IL", postalCode: "60645", lat: 42.0064, lng: -87.6926 },
  losangeles: {
    city: "Los Angeles",
    region: "CA",
    postalCode: "90035",
    lat: 34.0522,
    lng: -118.3831,
  },
  miami: { city: "Miami Beach", region: "FL", postalCode: "33140", lat: 25.8153, lng: -80.1275 },
  cleveland: {
    city: "Cleveland Heights",
    region: "OH",
    postalCode: "44118",
    lat: 41.52,
    lng: -81.5562,
  },
  passaic: { city: "Passaic", region: "NJ", postalCode: "07055", lat: 40.8568, lng: -74.1285 },
  detroit: { city: "Oak Park", region: "MI", postalCode: "48237", lat: 42.4595, lng: -83.1827 },
  atlanta: { city: "Atlanta", region: "GA", postalCode: "30329", lat: 33.8239, lng: -84.3199 },
  denver: { city: "Denver", region: "CO", postalCode: "80222", lat: 39.6737, lng: -104.9294 },
  jerusalem: { city: "Jerusalem", region: "", postalCode: "9101001", lat: 31.7683, lng: 35.2137 },
  bnaibrak: { city: "Bnei Brak", region: "", postalCode: "5120001", lat: 32.0807, lng: 34.8338 },
};

function stub(input: {
  slug: string;
  legalName: string;
  dba?: string;
  place: keyof typeof PLACES;
  categorySlugs: string[];
  ntee: string;
  rulingYear: number;
  budgetBand: string;
}): Json {
  const p = PLACES[input.place];
  return {
    slug: input.slug,
    legalName: input.legalName,
    dba: input.dba ?? null,
    ein: demoEin(),
    taxStatus: "us_501c3",
    usPartnerOrgSlug: null,
    claimStatus: "unclaimed",
    verificationLevel: "irs_listed",
    source: "irs_bmf",
    tagline: null,
    storyMd: null,
    logoUrl: null,
    heroUrl: null,
    website: null,
    phone: null,
    email: null,
    addressLine1: null,
    city: p.city,
    region: p.region,
    postalCode: p.postalCode,
    country: "US",
    lat: p.lat,
    lng: p.lng,
    rulingYear: input.rulingYear,
    nteeCode: input.ntee,
    budgetBand: input.budgetBand,
    categorySlugs: input.categorySlugs,
    departments: [],
    campaigns: [],
    paymentMethods: [],
    endorsements: [],
    isPublished: true,
    irsLastSyncedAt: daysAgo(6),
  };
}

const organizations: Json[] = [];

/* ------------------------------------------------------- claimed profiles */

organizations.push({
  slug: "ezras-shabbos-network",
  legalName: "Ezras Shabbos Network Inc.",
  dba: "Ezras Shabbos",
  ein: demoEin(),
  taxStatus: "us_501c3",
  usPartnerOrgSlug: null,
  claimStatus: "verified_contact",
  verificationLevel: "endorsed",
  source: "irs_bmf",
  tagline: "Weekly food packages for 640 families across Ocean County.",
  storyMd:
    "Ezras Shabbos began in 2009 with four families and a station wagon. Today a volunteer crew of ninety packs and delivers groceries every Thursday night, quietly, to households that would otherwise choose between rent and a Shabbos table.\n\nEvery family is referred by a rav, a principal or a social worker. No family is ever asked to appear in a photograph, and no name leaves the packing room.",
  logoUrl: null,
  heroUrl: null,
  website: "https://example.org/ezras-shabbos",
  phone: "(732) 555-0114",
  email: "office@example.org",
  addressLine1: "18 Cedar Bridge Ave",
  ...PLACES.lakewood,
  country: "US",
  rulingYear: 2009,
  nteeCode: "P600",
  budgetBand: "2m_10m",
  categorySlugs: ["food", "kimcha-dpischa"],
  departments: [
    {
      id: "esn-dept-packages",
      name: "Weekly Food Packages",
      description: "The core program: groceries delivered every Thursday to 640 households.",
      sortOrder: 1,
    },
    {
      id: "esn-dept-emergency",
      name: "Emergency Fund",
      description:
        "Same-week help for a family hit by a job loss, a hospitalisation or an eviction notice. Routed separately so it is never spent on operations.",
      sortOrder: 2,
    },
    {
      id: "esn-dept-logistics",
      name: "Vehicle & Logistics",
      description: "The two refrigerated vans, the warehouse lease and the fuel that moves it all.",
      sortOrder: 3,
    },
  ],
  campaigns: [
    {
      id: "esn-c1",
      slug: "sponsor-a-family",
      departmentId: "esn-dept-packages",
      title: "Sponsor a family for a month",
      description:
        "Four weeks of groceries for one household. The most common gift we receive, and the one we can plan around.",
      goalCents: null,
      raisedCents: null,
      raisedUpdatedAt: null,
      currency: "USD",
      startsAt: null,
      endsAt: null,
      matchMultiplier: null,
      matcherName: null,
      suggestedAmountsCents: [18000, 36000, 54000],
      status: "active",
    },
    {
      id: "esn-c2",
      slug: "yom-tov-drive",
      departmentId: "esn-dept-packages",
      title: "Yom Tov drive",
      description:
        "Meat, wine and staples for Rosh Hashana and Succos, on top of the ordinary weekly package.",
      goalCents: 5_000_000,
      raisedCents: 3_100_000,
      raisedUpdatedAt: daysAgo(3),
      currency: "USD",
      startsAt: daysAgo(40),
      endsAt: new Date(TODAY.getTime() + 30 * 86_400_000).toISOString(),
      matchMultiplier: 2,
      matcherName: "The Weinstock Family Foundation",
      suggestedAmountsCents: [5000, 18000, 100000],
      status: "active",
    },
    {
      id: "esn-c3",
      slug: "delivery-van",
      departmentId: "esn-dept-logistics",
      title: "Replacement delivery van",
      description:
        "Our 2011 van failed inspection in June. A refrigerated replacement runs $38,000 and covers roughly 180 deliveries a week.",
      goalCents: 3_800_000,
      raisedCents: 1_425_000,
      raisedUpdatedAt: daysAgo(11),
      currency: "USD",
      startsAt: daysAgo(70),
      endsAt: null,
      matchMultiplier: null,
      matcherName: null,
      suggestedAmountsCents: [10000, 50000, 250000],
      status: "active",
    },
  ],
  paymentMethods: [
    {
      id: "esn-pm1",
      type: "zelle",
      handle: "give@example.org",
      displayName: "Zelle — general fund",
      instructionsMd:
        "Send from your bank's Zelle screen to **give@example.org**. Put the campaign name in the memo so it reaches the right department.",
      externalUrl: null,
      isPrimary: true,
      departmentId: null,
      sortOrder: 1,
    },
    {
      id: "esn-pm2",
      type: "zelle",
      handle: "emergency@example.org",
      displayName: "Zelle — emergency fund only",
      instructionsMd:
        "This address is watched daily and is spent only on same-week family emergencies.",
      externalUrl: null,
      isPrimary: false,
      departmentId: "esn-dept-emergency",
      sortOrder: 2,
    },
    {
      id: "esn-pm3",
      type: "check",
      handle: "Ezras Shabbos Network Inc.",
      displayName: "Check by mail",
      instructionsMd:
        "Make payable to **Ezras Shabbos Network Inc.**\n\n18 Cedar Bridge Ave, Lakewood, NJ 08701",
      externalUrl: null,
      isPrimary: false,
      departmentId: null,
      sortOrder: 3,
    },
  ],
  endorsements: [
    {
      id: "esn-e1",
      endorserName: "Rabbi Y. Halberstam",
      endorserTitle: "Rav, Kehilas Bais Avrohom",
      quote:
        "I have referred families to Ezras Shabbos for eleven years. Not once has a family's name become known outside that room.",
      verifiedAt: daysAgo(120),
    },
  ],
  isPublished: true,
  irsLastSyncedAt: daysAgo(6),
});

organizations.push({
  slug: "keren-refuah-bikur-cholim",
  legalName: "Keren Refuah Bikur Cholim Inc.",
  dba: "Keren Refuah",
  ein: demoEin(),
  taxStatus: "us_501c3",
  usPartnerOrgSlug: null,
  claimStatus: "verified_contact",
  verificationLevel: "claim_verified",
  source: "irs_bmf",
  tagline: "Hospital apartments, hot meals and medical referrals in five boroughs.",
  storyMd:
    "Families come to New York for treatment and discover the second problem: where to sleep, what to eat, and who to ask. Keren Refuah keeps eleven apartments within walking distance of four hospitals, runs a kosher meal delivery into six units, and staffs a referral line that has taken more than 14,000 calls.",
  logoUrl: null,
  heroUrl: null,
  website: "https://example.org/keren-refuah",
  phone: "(718) 555-0187",
  email: "info@example.org",
  addressLine1: "1427 48th Street",
  ...PLACES.brooklyn,
  country: "US",
  rulingYear: 1998,
  nteeCode: "P580",
  budgetBand: "2m_10m",
  categorySlugs: ["bikur-cholim"],
  departments: [
    {
      id: "krb-dept-apartments",
      name: "Hospital Apartments",
      description: "Eleven furnished units, no charge, no questions about ability to pay.",
      sortOrder: 1,
    },
    {
      id: "krb-dept-meals",
      name: "Kosher Meal Delivery",
      description: "Hot meals into six hospital units, seven days a week.",
      sortOrder: 2,
    },
    {
      id: "krb-dept-referral",
      name: "Referral Line",
      description: "Two full-time coordinators who know which specialist takes which plan.",
      sortOrder: 3,
    },
  ],
  campaigns: [
    {
      id: "krb-c1",
      slug: "one-night",
      departmentId: "krb-dept-apartments",
      title: "Sponsor one night",
      description: "A night in an apartment for a family whose child is in treatment.",
      goalCents: null,
      raisedCents: null,
      raisedUpdatedAt: null,
      currency: "USD",
      startsAt: null,
      endsAt: null,
      matchMultiplier: null,
      matcherName: null,
      suggestedAmountsCents: [10000, 25000, 50000],
      status: "active",
    },
    {
      id: "krb-c2",
      slug: "twelfth-apartment",
      departmentId: "krb-dept-apartments",
      title: "The twelfth apartment",
      description:
        "A two-bedroom near Columbia came available in May. First year of rent, furnishing and utilities.",
      goalCents: 9_600_000,
      raisedCents: 7_320_000,
      raisedUpdatedAt: daysAgo(8),
      currency: "USD",
      startsAt: daysAgo(95),
      endsAt: null,
      matchMultiplier: null,
      matcherName: null,
      suggestedAmountsCents: [18000, 100000, 500000],
      status: "active",
    },
  ],
  paymentMethods: [
    {
      id: "krb-pm1",
      type: "zelle",
      handle: "donate@example.org",
      displayName: "Zelle",
      instructionsMd: null,
      externalUrl: null,
      isPrimary: true,
      departmentId: null,
      sortOrder: 1,
    },
    {
      id: "krb-pm2",
      type: "paypal",
      handle: "kerenrefuahdemo",
      displayName: "PayPal",
      instructionsMd: null,
      externalUrl: null,
      isPrimary: false,
      departmentId: null,
      sortOrder: 2,
    },
    {
      id: "krb-pm3",
      type: "wire",
      handle: "Contact the office for wire details",
      displayName: "Bank wire",
      instructionsMd: "Call the office on (718) 555-0187 and ask for Mrs. Traube.",
      externalUrl: null,
      isPrimary: false,
      departmentId: null,
      sortOrder: 3,
    },
  ],
  endorsements: [],
  isPublished: true,
  irsLastSyncedAt: daysAgo(6),
});

organizations.push({
  slug: "yad-lkallah-of-baltimore",
  legalName: "Yad L'Kallah of Baltimore Inc.",
  dba: null,
  ein: demoEin(),
  taxStatus: "us_501c3",
  usPartnerOrgSlug: null,
  claimStatus: "verified_contact",
  verificationLevel: "claim_verified",
  source: "irs_bmf",
  tagline: "Wedding and first-apartment costs for families who cannot cover them.",
  storyMd:
    "A wedding should not begin with a loan the family cannot service. Yad L'Kallah works with six local rabbanim who refer families confidentially; we cover hall deposits, basic furniture and linens, and never the extras.",
  logoUrl: null,
  heroUrl: null,
  website: null,
  phone: "(410) 555-0132",
  email: "office@example.org",
  addressLine1: "6210 Park Heights Ave",
  ...PLACES.baltimore,
  country: "US",
  rulingYear: 2004,
  nteeCode: "P600",
  budgetBand: "500k_2m",
  categorySlugs: ["hachnasas-kallah"],
  departments: [
    {
      id: "ylk-dept-wedding",
      name: "Wedding Costs",
      description: "Hall deposit, catering shortfall, sheitel and gown.",
      sortOrder: 1,
    },
    {
      id: "ylk-dept-home",
      name: "First Home Setup",
      description: "Beds, a table, a fridge, linen. The list is fixed and published.",
      sortOrder: 2,
    },
  ],
  campaigns: [
    {
      id: "ylk-c1",
      slug: "elul-cycle",
      departmentId: "ylk-dept-wedding",
      title: "Elul cycle — nine weddings",
      description: "Nine families with chasunos between Elul and Cheshvan.",
      goalCents: 18_000_000,
      raisedCents: 6_480_000,
      raisedUpdatedAt: daysAgo(2),
      currency: "USD",
      startsAt: daysAgo(25),
      endsAt: new Date(TODAY.getTime() + 60 * 86_400_000).toISOString(),
      matchMultiplier: 2,
      matcherName: "Anonymous, Baltimore",
      suggestedAmountsCents: [18000, 36000, 180000],
      status: "active",
    },
  ],
  paymentMethods: [
    {
      id: "ylk-pm1",
      type: "zelle",
      handle: "(410) 555-0132",
      displayName: "Zelle — by phone number",
      instructionsMd: "Zelle to the office phone number. The account name shows as YAD LKALLAH.",
      externalUrl: null,
      isPrimary: true,
      departmentId: null,
      sortOrder: 1,
    },
    {
      id: "ylk-pm2",
      type: "check",
      handle: "Yad L'Kallah of Baltimore Inc.",
      displayName: "Check by mail",
      instructionsMd: "6210 Park Heights Ave, Baltimore, MD 21215",
      externalUrl: null,
      isPrimary: false,
      departmentId: null,
      sortOrder: 2,
    },
  ],
  endorsements: [],
  isPublished: true,
  irsLastSyncedAt: daysAgo(6),
});

organizations.push({
  slug: "gemach-hachnosas-orchim-monsey",
  legalName: "Gemach Keren Hashem of Monsey Inc.",
  dba: "Keren Hashem Gemach",
  ein: demoEin(),
  taxStatus: "us_501c3",
  usPartnerOrgSlug: null,
  claimStatus: "claimed",
  verificationLevel: "claimed",
  source: "irs_bmf",
  tagline: "Interest-free loans up to $10,000, repaid on a schedule you set.",
  storyMd:
    "A free loan is not charity and is not meant to feel like it. We hold roughly $2.4M in a revolving fund; 96% of it is repaid and lent again. Applications are reviewed within four business days.",
  logoUrl: null,
  heroUrl: null,
  website: null,
  phone: "(845) 555-0146",
  email: "gemach@example.org",
  addressLine1: null,
  ...PLACES.monsey,
  country: "US",
  rulingYear: 1991,
  nteeCode: "P600",
  budgetBand: "500k_2m",
  categorySlugs: ["gemach"],
  departments: [
    {
      id: "gkh-dept-fund",
      name: "Revolving Loan Fund",
      description: "Deposits into the fund are lent out and lent again.",
      sortOrder: 1,
    },
  ],
  campaigns: [
    {
      id: "gkh-c1",
      slug: "grow-the-fund",
      departmentId: "gkh-dept-fund",
      title: "Grow the fund",
      description:
        "Every dollar added is lent roughly 1.6 times a year. We are turning away applicants for the first time since 2019.",
      goalCents: 50_000_000,
      raisedCents: 11_000_000,
      raisedUpdatedAt: daysAgo(19),
      currency: "USD",
      startsAt: daysAgo(150),
      endsAt: null,
      matchMultiplier: null,
      matcherName: null,
      suggestedAmountsCents: [10000, 100000, 1000000],
      status: "active",
    },
  ],
  paymentMethods: [
    {
      id: "gkh-pm1",
      type: "zelle",
      handle: "gemach@example.org",
      displayName: "Zelle",
      instructionsMd: null,
      externalUrl: null,
      isPrimary: true,
      departmentId: null,
      sortOrder: 1,
    },
  ],
  endorsements: [],
  isPublished: true,
  irsLastSyncedAt: daysAgo(6),
});

organizations.push({
  slug: "yesodei-hatorah-academy",
  legalName: "Yesodei HaTorah Academy of Chicago",
  dba: null,
  ein: demoEin(),
  taxStatus: "us_501c3",
  usPartnerOrgSlug: null,
  claimStatus: "verified_contact",
  verificationLevel: "claim_verified",
  source: "irs_bmf",
  tagline: "A 340-student day school where a third of families are on tuition assistance.",
  storyMd:
    "Yesodei HaTorah has never turned away a family for inability to pay, which is a policy with a price tag. The scholarship fund is that price tag, published in full every year.",
  logoUrl: null,
  heroUrl: null,
  website: "https://example.org/yesodei",
  phone: "(773) 555-0198",
  email: "development@example.org",
  addressLine1: "2840 W Devon Ave",
  ...PLACES.chicago,
  country: "US",
  rulingYear: 1976,
  nteeCode: "B20",
  budgetBand: "2m_10m",
  categorySlugs: ["chinuch"],
  departments: [
    {
      id: "yha-dept-scholarship",
      name: "Scholarship Fund",
      description: "Tuition assistance for 112 of our 340 families.",
      sortOrder: 1,
    },
    {
      id: "yha-dept-building",
      name: "Building & Safety",
      description: "The 1974 building, its boiler, and the security upgrades required in 2024.",
      sortOrder: 2,
    },
    {
      id: "yha-dept-special-ed",
      name: "Learning Support",
      description: "Three resource-room staff and the testing that places children correctly.",
      sortOrder: 3,
    },
  ],
  campaigns: [
    {
      id: "yha-c1",
      slug: "scholarship-2026",
      departmentId: "yha-dept-scholarship",
      title: "Scholarship fund 5786",
      description: "The gap between what families can pay and what a seat costs.",
      goalCents: 42_000_000,
      raisedCents: 15_540_000,
      raisedUpdatedAt: daysAgo(5),
      currency: "USD",
      startsAt: daysAgo(60),
      endsAt: null,
      matchMultiplier: null,
      matcherName: null,
      suggestedAmountsCents: [18000, 100000, 500000],
      status: "active",
    },
    {
      id: "yha-c2",
      slug: "boiler",
      departmentId: "yha-dept-building",
      title: "Replace the boiler",
      description: "Condemned in March. We ran on rentals through the spring.",
      goalCents: 11_500_000,
      raisedCents: 11_500_000,
      raisedUpdatedAt: daysAgo(30),
      currency: "USD",
      startsAt: daysAgo(200),
      endsAt: daysAgo(28),
      matchMultiplier: null,
      matcherName: null,
      suggestedAmountsCents: [],
      status: "complete",
    },
  ],
  paymentMethods: [
    {
      id: "yha-pm1",
      type: "zelle",
      handle: "development@example.org",
      displayName: "Zelle",
      instructionsMd: null,
      externalUrl: null,
      isPrimary: true,
      departmentId: null,
      sortOrder: 1,
    },
    {
      id: "yha-pm2",
      type: "external",
      handle: "example.org/yesodei/donate",
      displayName: "Our own donation page",
      instructionsMd: null,
      externalUrl: "https://example.org/yesodei/donate",
      isPrimary: false,
      departmentId: null,
      sortOrder: 2,
    },
  ],
  endorsements: [],
  isPublished: true,
  irsLastSyncedAt: daysAgo(6),
});

organizations.push({
  slug: "hatzalah-of-the-western-suburbs",
  legalName: "Volunteer Hatzalah of the Western Suburbs",
  dba: null,
  ein: demoEin(),
  taxStatus: "us_501c3",
  usPartnerOrgSlug: null,
  claimStatus: "verified_contact",
  verificationLevel: "claim_verified",
  source: "irs_bmf",
  tagline: "62 volunteer EMTs. Average response time under four minutes.",
  storyMd:
    "Every member is a volunteer. What costs money is equipment, radios, training hours and the two ambulances themselves.",
  logoUrl: null,
  heroUrl: null,
  website: null,
  phone: "(248) 555-0175",
  email: "info@example.org",
  addressLine1: null,
  ...PLACES.detroit,
  country: "US",
  rulingYear: 2002,
  nteeCode: "E62",
  budgetBand: "500k_2m",
  categorySlugs: ["hatzalah"],
  departments: [
    {
      id: "hws-dept-equipment",
      name: "Equipment & Radios",
      description: "Defibrillators, oxygen, trauma bags, the radio network.",
      sortOrder: 1,
    },
    {
      id: "hws-dept-training",
      name: "Training",
      description: "EMT certification and recertification for volunteers.",
      sortOrder: 2,
    },
  ],
  campaigns: [
    {
      id: "hws-c1",
      slug: "defibrillators",
      departmentId: "hws-dept-equipment",
      title: "Twelve replacement defibrillators",
      description: "Our current units reach end-of-service in December.",
      goalCents: 5_400_000,
      raisedCents: 4_860_000,
      raisedUpdatedAt: daysAgo(1),
      currency: "USD",
      startsAt: daysAgo(45),
      endsAt: new Date(TODAY.getTime() + 14 * 86_400_000).toISOString(),
      matchMultiplier: 3,
      matcherName: "Three anonymous families",
      suggestedAmountsCents: [3600, 18000, 45000],
      status: "active",
    },
  ],
  paymentMethods: [
    {
      id: "hws-pm1",
      type: "zelle",
      handle: "info@example.org",
      displayName: "Zelle",
      instructionsMd: null,
      externalUrl: null,
      isPrimary: true,
      departmentId: null,
      sortOrder: 1,
    },
    {
      id: "hws-pm2",
      type: "venmo",
      handle: "hatzalah-ws-demo",
      displayName: "Venmo",
      instructionsMd: null,
      externalUrl: null,
      isPrimary: false,
      departmentId: null,
      sortOrder: 2,
    },
  ],
  endorsements: [],
  isPublished: true,
  irsLastSyncedAt: daysAgo(6),
});

organizations.push({
  slug: "kollel-ohr-yisroel-passaic",
  legalName: "Kollel Ohr Yisroel of Passaic",
  dba: null,
  ein: demoEin(),
  taxStatus: "us_501c3",
  usPartnerOrgSlug: null,
  claimStatus: "claimed",
  verificationLevel: "claimed",
  source: "irs_bmf",
  tagline: "Twenty-two full-time avreichim and an evening beis midrash open to the town.",
  storyMd:
    "The kollel is not a closed room. Twenty-two avreichim learn through the day; from eight in the evening the same beis midrash fills with balebatim and a chavrusa programme that has run for fourteen years.",
  logoUrl: null,
  heroUrl: null,
  website: null,
  phone: null,
  email: "kollel@example.org",
  addressLine1: null,
  ...PLACES.passaic,
  country: "US",
  rulingYear: 2011,
  nteeCode: "X30",
  budgetBand: "500k_2m",
  categorySlugs: ["kollel"],
  departments: [
    {
      id: "koy-dept-stipends",
      name: "Avreichim Stipends",
      description: "The monthly stipend for twenty-two families.",
      sortOrder: 1,
    },
  ],
  campaigns: [
    {
      id: "koy-c1",
      slug: "adopt-a-chavrusa",
      departmentId: "koy-dept-stipends",
      title: "Adopt a chavrusa",
      description: "Monthly support for one avreich, with a written update twice a year.",
      goalCents: null,
      raisedCents: null,
      raisedUpdatedAt: null,
      currency: "USD",
      startsAt: null,
      endsAt: null,
      matchMultiplier: null,
      matcherName: null,
      suggestedAmountsCents: [10000, 25000, 50000],
      status: "active",
    },
    {
      id: "koy-c2",
      slug: "winter-zman-2024",
      departmentId: "koy-dept-stipends",
      title: "Winter zman appeal",
      description: "Left up past its end date — a good example of what the staleness rule catches.",
      goalCents: 8_000_000,
      raisedCents: 2_100_000,
      raisedUpdatedAt: daysAgo(88),
      currency: "USD",
      startsAt: daysAgo(300),
      endsAt: daysAgo(120),
      matchMultiplier: null,
      matcherName: null,
      suggestedAmountsCents: [],
      status: "flagged_stale",
    },
  ],
  paymentMethods: [
    {
      id: "koy-pm1",
      type: "zelle",
      handle: "kollel@example.org",
      displayName: "Zelle",
      instructionsMd: null,
      externalUrl: null,
      isPrimary: true,
      departmentId: null,
      sortOrder: 1,
    },
  ],
  endorsements: [],
  isPublished: true,
  irsLastSyncedAt: daysAgo(6),
});

organizations.push({
  slug: "beis-yesomim-fund",
  legalName: "The Beis Yesomim Fund Inc.",
  dba: null,
  ein: demoEin(),
  taxStatus: "us_501c3",
  usPartnerOrgSlug: null,
  claimStatus: "verified_contact",
  verificationLevel: "endorsed",
  source: "irs_bmf",
  tagline: "Standing beside 84 families who have lost a parent.",
  storyMd:
    "We do three things and only three: a monthly stipend that does not taper, camp and yeshiva tuition for the children, and a call before every Yom Tov from someone who remembers the family's name.",
  logoUrl: null,
  heroUrl: null,
  website: "https://example.org/beis-yesomim",
  phone: "(305) 555-0163",
  email: "office@example.org",
  addressLine1: null,
  ...PLACES.miami,
  country: "US",
  rulingYear: 2013,
  nteeCode: "P600",
  budgetBand: "500k_2m",
  categorySlugs: ["yesomim"],
  departments: [
    {
      id: "byf-dept-stipend",
      name: "Monthly Stipends",
      description: "84 families, paid on the first of the month, every month.",
      sortOrder: 1,
    },
    {
      id: "byf-dept-tuition",
      name: "Tuition & Camp",
      description: "School and summer costs for 191 children.",
      sortOrder: 2,
    },
  ],
  campaigns: [
    {
      id: "byf-c1",
      slug: "yom-tov-stipend",
      departmentId: "byf-dept-stipend",
      title: "Yom Tov stipend",
      description: "The extra month's payment before Tishrei.",
      goalCents: 12_000_000,
      raisedCents: 4_200_000,
      raisedUpdatedAt: daysAgo(4),
      currency: "USD",
      startsAt: daysAgo(20),
      endsAt: new Date(TODAY.getTime() + 25 * 86_400_000).toISOString(),
      matchMultiplier: null,
      matcherName: null,
      suggestedAmountsCents: [18000, 36000, 100000],
      status: "active",
    },
  ],
  paymentMethods: [
    {
      id: "byf-pm1",
      type: "zelle",
      handle: "office@example.org",
      displayName: "Zelle",
      instructionsMd: null,
      externalUrl: null,
      isPrimary: true,
      departmentId: null,
      sortOrder: 1,
    },
    {
      id: "byf-pm2",
      type: "paypal",
      handle: "beisyesomimdemo",
      displayName: "PayPal",
      instructionsMd: null,
      externalUrl: null,
      isPrimary: false,
      departmentId: null,
      sortOrder: 2,
    },
  ],
  endorsements: [
    {
      id: "byf-e1",
      endorserName: "Rabbi D. Mandelbaum",
      endorserTitle: "Rosh Kollel, Miami Beach",
      quote: "The stipend arrives on the first. In eight years I have not heard of it being late.",
      verifiedAt: daysAgo(400),
    },
    {
      id: "byf-e2",
      endorserName: "Mrs. S. Kaufman, CPA",
      endorserTitle: "Volunteer treasurer, 2013–2024",
      quote: "Overhead has never exceeded six percent. The audited statements are on the website.",
      verifiedAt: daysAgo(210),
    },
  ],
  isPublished: true,
  irsLastSyncedAt: daysAgo(6),
});

organizations.push({
  slug: "american-friends-of-tiferes-yerushalayim",
  legalName: "American Friends of Tiferes Yerushalayim Inc.",
  dba: null,
  ein: demoEin(),
  taxStatus: "us_501c3",
  usPartnerOrgSlug: null,
  claimStatus: "verified_contact",
  verificationLevel: "claim_verified",
  source: "irs_bmf",
  tagline: "The US entity through which American donors reach Tiferes Yerushalayim.",
  storyMd:
    "We exist for one reason: so that a US donor can support the work in Jerusalem and receive a receipt that stands up on a US return.",
  logoUrl: null,
  heroUrl: null,
  website: null,
  phone: "(718) 555-0121",
  email: "aftydemo@example.org",
  addressLine1: null,
  ...PLACES.brooklyn,
  country: "US",
  rulingYear: 1994,
  nteeCode: "X30",
  budgetBand: "500k_2m",
  categorySlugs: ["israel", "chinuch"],
  departments: [],
  campaigns: [],
  paymentMethods: [
    {
      id: "afty-pm1",
      type: "zelle",
      handle: "aftydemo@example.org",
      displayName: "Zelle",
      instructionsMd: null,
      externalUrl: null,
      isPrimary: true,
      departmentId: null,
      sortOrder: 1,
    },
  ],
  endorsements: [],
  isPublished: true,
  irsLastSyncedAt: daysAgo(6),
});

organizations.push({
  slug: "tiferes-yerushalayim",
  legalName: "עמותת תפארת ירושלים",
  dba: "Tiferes Yerushalayim",
  ein: null,
  taxStatus: "israeli_amuta",
  usPartnerOrgSlug: "american-friends-of-tiferes-yerushalayim",
  claimStatus: "verified_contact",
  verificationLevel: "claim_verified",
  source: "self_submitted",
  tagline: "Food, tuition and heating support for 300 families in Jerusalem.",
  storyMd:
    "Registered as an Israeli amuta with 46א status. A gift sent directly from the United States is generally **not** deductible on a US return — American donors should give through American Friends of Tiferes Yerushalayim instead, which is listed alongside this profile.",
  logoUrl: null,
  heroUrl: null,
  website: null,
  phone: null,
  email: "office@example.org",
  addressLine1: null,
  ...PLACES.jerusalem,
  country: "IL",
  rulingYear: 1988,
  nteeCode: null,
  budgetBand: "500k_2m",
  categorySlugs: ["israel", "food"],
  departments: [
    {
      id: "ty-dept-food",
      name: "Food Assistance",
      description: "Monthly vouchers for 300 families.",
      sortOrder: 1,
    },
  ],
  campaigns: [
    {
      id: "ty-c1",
      slug: "winter-heating",
      departmentId: "ty-dept-food",
      title: "Winter heating fund",
      description: "Gas and electricity for families in Jerusalem's older stone buildings.",
      goalCents: 30_000_000,
      raisedCents: 9_000_000,
      raisedUpdatedAt: daysAgo(14),
      currency: "ILS",
      startsAt: daysAgo(30),
      endsAt: null,
      matchMultiplier: null,
      matcherName: null,
      suggestedAmountsCents: [],
      status: "active",
    },
  ],
  paymentMethods: [
    {
      id: "ty-pm1",
      type: "external",
      handle: "example.org/tiferes/give",
      displayName: "Israeli donation page (ILS)",
      instructionsMd: null,
      externalUrl: "https://example.org/tiferes/give",
      isPrimary: true,
      departmentId: null,
      sortOrder: 1,
    },
  ],
  endorsements: [],
  isPublished: true,
  irsLastSyncedAt: null,
});

/* ---------------------------------------------------------- unclaimed stubs */

const STUBS: Parameters<typeof stub>[0][] = [
  {
    slug: "bais-yaakov-of-the-heights",
    legalName: "Bais Yaakov of the Heights",
    place: "cleveland",
    categorySlugs: ["chinuch"],
    ntee: "B20",
    rulingYear: 1969,
    budgetBand: "2m_10m",
  },
  {
    slug: "chesed-shel-emes-of-oak-park",
    legalName: "Chesed Shel Emes of Oak Park Inc.",
    place: "detroit",
    categorySlugs: ["bikur-cholim"],
    ntee: "P600",
    rulingYear: 1985,
    budgetBand: "under_100k",
  },
  {
    slug: "kimcha-dpischa-of-denver",
    legalName: "Kimcha D'Pischa Fund of Denver",
    place: "denver",
    categorySlugs: ["kimcha-dpischa", "food"],
    ntee: "P600",
    rulingYear: 2001,
    budgetBand: "100k_500k",
  },
  {
    slug: "mikvah-israel-of-atlanta",
    legalName: "Mikvah Israel of Atlanta Inc.",
    place: "atlanta",
    categorySlugs: ["shul-mikvah"],
    ntee: "X30",
    rulingYear: 1997,
    budgetBand: "100k_500k",
  },
  {
    slug: "congregation-ohel-zichron",
    legalName: "Congregation Ohel Zichron",
    place: "monsey",
    categorySlugs: ["shul-mikvah"],
    ntee: "X30",
    rulingYear: 1978,
    budgetBand: "100k_500k",
  },
  {
    slug: "yeshiva-toras-emes-of-passaic",
    legalName: "Yeshiva Toras Emes of Passaic",
    place: "passaic",
    categorySlugs: ["chinuch", "kollel"],
    ntee: "B20",
    rulingYear: 1988,
    budgetBand: "2m_10m",
  },
  {
    slug: "agudath-chesed-of-los-angeles",
    legalName: "Agudath Chesed of Los Angeles",
    place: "losangeles",
    categorySlugs: ["food"],
    ntee: "P600",
    rulingYear: 1992,
    budgetBand: "500k_2m",
  },
  {
    slug: "hachnosas-orchim-of-brooklyn",
    legalName: "Hachnosas Orchim Society of Brooklyn Inc.",
    place: "brooklyn",
    categorySlugs: ["bikur-cholim", "food"],
    ntee: "P600",
    rulingYear: 1964,
    budgetBand: "100k_500k",
  },
  {
    slug: "keren-almanos-vyesomim",
    legalName: "Keren Almanos V'Yesomim Inc.",
    place: "lakewood",
    categorySlugs: ["yesomim"],
    ntee: "P600",
    rulingYear: 2016,
    budgetBand: "under_100k",
  },
  {
    slug: "gemach-zichron-shmuel",
    legalName: "Gemach Zichron Shmuel",
    place: "baltimore",
    categorySlugs: ["gemach"],
    ntee: "P600",
    rulingYear: 2007,
    budgetBand: "under_100k",
  },
  {
    slug: "campus-kiruv-initiative",
    legalName: "Campus Kiruv Initiative Inc.",
    place: "chicago",
    categorySlugs: ["kiruv"],
    ntee: "X30",
    rulingYear: 2010,
    budgetBand: "500k_2m",
  },
  {
    slug: "ohr-ahavas-torah-outreach",
    legalName: "Ohr Ahavas Torah Outreach Center",
    place: "miami",
    categorySlugs: ["kiruv", "kollel"],
    ntee: "X30",
    rulingYear: 2005,
    budgetBand: "100k_500k",
  },
  {
    slug: "bikur-cholim-of-the-west-side",
    legalName: "Bikur Cholim of the West Side Inc.",
    place: "losangeles",
    categorySlugs: ["bikur-cholim"],
    ntee: "P580",
    rulingYear: 1999,
    budgetBand: "500k_2m",
  },
  {
    slug: "hatzalah-of-greater-atlanta",
    legalName: "Hatzalah of Greater Atlanta Inc.",
    place: "atlanta",
    categorySlugs: ["hatzalah"],
    ntee: "E62",
    rulingYear: 2014,
    budgetBand: "100k_500k",
  },
  {
    slug: "tomchei-yisroel-of-cleveland",
    legalName: "Tomchei Yisroel of Cleveland",
    place: "cleveland",
    categorySlugs: ["food", "kimcha-dpischa"],
    ntee: "P600",
    rulingYear: 1983,
    budgetBand: "500k_2m",
  },
  {
    slug: "hachnasas-kallah-of-denver",
    legalName: "Hachnasas Kallah Society of Denver",
    place: "denver",
    categorySlugs: ["hachnasas-kallah"],
    ntee: "P600",
    rulingYear: 2018,
    budgetBand: "under_100k",
  },
  {
    slug: "beis-medrash-of-bnei-brak-friends",
    legalName: "American Friends of Beis Medrash Bnei Brak",
    place: "brooklyn",
    categorySlugs: ["israel", "kollel"],
    ntee: "X30",
    rulingYear: 1996,
    budgetBand: "100k_500k",
  },
  {
    slug: "shomrei-mishmeres-jerusalem-fund",
    legalName: "Shomrei Mishmeres Jerusalem Fund Inc.",
    place: "monsey",
    categorySlugs: ["israel"],
    ntee: "X30",
    rulingYear: 2008,
    budgetBand: "100k_500k",
  },
];

for (const s of STUBS) organizations.push(stub(s));

/* ------------------------------------------------------------------ write */

const out = {
  $comment:
    "DEMO FIXTURE. Every organization here is fictional and every payment handle is a placeholder. Replace by running scripts/ingest-bmf.ts against the IRS Exempt Organizations Business Master File.",
  isDemoData: true,
  generatedAt: TODAY.toISOString(),
  organizations,
};

const target = resolve(process.cwd(), "src/data/seed-organizations.json");
mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, `${JSON.stringify(out, null, 2)}\n`);
console.log(`Wrote ${organizations.length} organizations to ${target}`);
